swagger: "2.0"
info:
  version: "1.0.0"
  title: "Swagger assignment"
host: "api.muzicplayz.com"
basePath: "/v3"
schemes:
- "https"

paths:
  /playlist:
    post:
     parameters:
     - in: "body"
       name: "body"
       description: "hello world"
       required: true
       schema:
         $ref: '#/definitions/user'
     responses:
      "405":
        description: "invalid"

definitions:
  Order:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      petId:
        type: "integer"
        format: "int64"
      quantity:
        type: "integer"
        format: "int32"
      shipDate:
        type: "string"
        format: "date-time"
  
  Category:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "integer"
  user:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
    xml:
      name: "user"
    
 

          
  